name: Deploy Frontend to Render

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Frontend Deploy Hook
        run: curl -X POST ${{ secrets.RENDER_FRONTEND_HOOK_URL }}
